# Generated by Django 6.0.2 on 2026-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, default='Наблюдатель', max_length=50, null=True, verbose_name='Ранг'),
        ),
    ]
