import { useEffect, useState } from 'react';
import { Heart, Star, Trash2 } from 'lucide-react';
import { Avatar, Button, EmptyState, Skeleton, Textarea } from '../../../shared/ui';
import { postInteractionsApi } from '../api/postInteractionsApi';
import { apiMessage, relativeDate } from '../../../shared/lib/format';
import { useAuth } from '../../auth/model/AuthContext';

export function Rating({ post, onChange }) { const [busy, setBusy] = useState(false); const rate = async (value) => { const previous = { rating_avg: post.rating_avg, rating_count: post.rating_count }; onChange({ rating_avg: value, rating_count: (post.rating_count || 0) + 1 }); setBusy(true); try { const { data } = await postInteractionsApi.rate(post.id, value); onChange(data); } catch { onChange(previous); } finally { setBusy(false); } }; return <div className="rating-control" aria-label="Оценка публикации">{[1, 2, 3, 4, 5].map((value) => <button key={value} disabled={busy} onClick={() => rate(value)} aria-label={`Оценить на ${value}`}><Star size={15} fill={value <= Math.round(post.rating_avg || 0) ? 'currentColor' : 'none'}/></button>)}<small>{Number(post.rating_avg || 0).toFixed(1)} · {post.rating_count || 0}</small></div>; }
export function CommentThread({ postId }) { const { user } = useAuth(); const [state, setState] = useState({ items: [], loading: true, error: '' }); const [text, setText] = useState(''); const [sending, setSending] = useState(false); const load = async () => { setState((s) => ({ ...s, loading: true })); try { const { data } = await postInteractionsApi.comments(postId); setState({ items: data.results || data, loading: false, error: '' }); } catch (e) { setState((s) => ({ ...s, loading: false, error: apiMessage(e) })); } }; useEffect(() => { load(); }, [postId]); const add = async (e) => { e.preventDefault(); if (!text.trim()) return; setSending(true); try { const { data } = await postInteractionsApi.createComment(postId, text.trim()); setState((s) => ({ ...s, items: [...s.items, data] })); setText(''); } finally { setSending(false); } }; const remove = async (id) => { const previous = state.items; setState((s) => ({ ...s, items: s.items.filter((x) => x.id !== id) })); try { await postInteractionsApi.deleteComment(id); } catch { setState((s) => ({ ...s, items: previous })); } }; const like = async (comment) => { const previous = comment; setState((s) => ({ ...s, items: s.items.map((x) => x.id === comment.id ? { ...x, is_liked: !x.is_liked, likes_count: x.likes_count + (x.is_liked ? -1 : 1) } : x) })); try { await postInteractionsApi.likeComment(postId, comment.id); } catch { setState((s) => ({ ...s, items: s.items.map((x) => x.id === comment.id ? previous : x) })); } }; return <section className="comments"><h3>Комментарии</h3><form onSubmit={add}><Textarea aria-label="Текст комментария" placeholder="Добавить комментарий…" rows="2" value={text} onChange={(e) => setText(e.target.value)}/><Button type="submit" loading={sending}>Отправить</Button></form>{state.loading && <Skeleton className="line"/>}{state.error && <p className="form-error">{state.error}</p>}{!state.loading && !state.error && !state.items.length && <EmptyState title="Комментариев пока нет" description="Начните обсуждение первым."/>}<div className="comment-list">{state.items.map((comment) => <article className="comment" key={comment.id}><Avatar user={comment.author}/><div><strong>{comment.author?.first_name || comment.author?.username}</strong><small>@{comment.author?.username} · {relativeDate(comment.created_at)}</small><p>{comment.text}</p><Button variant={comment.is_liked ? 'active' : 'ghost'} onClick={() => like(comment)}><Heart size={14}/> {comment.likes_count || 0}</Button>{user?.id === comment.author?.id && <Button variant="ghost" onClick={() => remove(comment.id)} aria-label="Удалить комментарий"><Trash2 size={14}/></Button>}</div></article>)}</div></section>; }
